project:
  type: website
  output-dir: "."

website:
  title: "MOOREA MCKINSEY" 
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: R Basics
        href: danl-200-quarto.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Moorea Mckinsey, 2024"

format:
  html:
    theme: 
      light: morph
      dark: morph
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
